#
# Copyright (C) 2014 Alex Smith
#
# Permission to use, copy, modify, and/or distribute this software for any
# purpose with or without fee is hereby granted, provided that the above
# copyright notice and this permission notice appear in all copies.
#
# THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES
# WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF
# MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR
# ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
# WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN
# ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF
# OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.
#

Import('config', 'defaults', 'env')
from util import FeatureSources

sources = FeatureSources(config, [
    'relocate.c',
    'start.S',
])

# Set the linker script path.
env['LDSCRIPT'] = env.LDScript('link.ld', 'link.ld.in')

# GCC requires -maccumulate-outgoing-args in conjunction with ms_abi.
if not env['IS_CLANG']:
    env['CCFLAGS'] += ['-maccumulate-outgoing-args']

# Build the final EFI binary.
loader = env.Command(env['OUTDIR'].File('bootx64.efi'), env['LOADER'],
    Action('$OBJCOPY -j .text -j .reloc -j .data -j .dynamic -j .rela.dyn ' +
        '-j .dynsym -j .bss --target=efi-app-x86_64 ' +
        '$SOURCE $TARGET', '$GENCOMSTR'))
defaults.append(loader)

Return('sources')
