#
# SPDX-FileCopyrightText: (C) Alex Smith <alex@alex-smith.me.uk>
# SPDX-License-Identifier: ISC
#

import os

Import('env')

def build_utility(name, sources):
    env.Program(env['OUTDIR'].File(name), sources)

def build_script(name, sources):
    subst_dict = {
        '@KBOOT_LIBDIR@': env['LIBDIR'],
        '@KBOOT_LOADER_VERSION@': env['VERSION'],
    }

    target = env.Substfile(env['OUTDIR'].File(name), sources, SUBST_DICT = subst_dict)
    env.AddPostAction(target, env.Action(lambda target, source, env: os.chmod(str(target[0]), 0o755), None))

build_utility('kboot-install', ['install.c'])
build_script('kboot-mkiso', ['mkiso.in'])
