#
# SPDX-FileCopyrightText: (C) Alex Smith <alex@alex-smith.me.uk>
# SPDX-License-Identifier: ISC
#

Import('config', 'env')
from util import FeatureSources

sources = FeatureSources(config, [
    'relocate.c',
    'start.S',
])

# Set the linker script path.
env['LDSCRIPT'] = env.LDScript('link.ld', 'link.ld.in')

# The EFI binary must be relocatable, so on 64-bit this means we must build
# position independent code.
env['CCFLAGS'] += ['-fpic']
env['ASFLAGS'] += ['-fpic']

# Build the final EFI binary.
env.Command(
    env['OUTDIR'].File('kbootx64.efi'),
    env['KBOOT'],
    Action(
        '$OBJCOPY -j .text -j .reloc -j .data -j .dynamic -j .rela ' +
            '-j .dynsym -j .bss --target=efi-app-x86_64 $SOURCE $TARGET',
        '$GENCOMSTR'))

Return('sources')
