#
# SPDX-FileCopyrightText: (C) Alex Smith <alex@alex-smith.me.uk>
# SPDX-License-Identifier: ISC
#

vars = ['config', 'env']

Import(*vars)
from util import FeatureSources

sources = FeatureSources(config, [
    'loader/efi.c',
    'loader/kboot.c',

    'console.c',
    'device.c',
    'disk.c',
    'memory.c',
    'net.c',
    'platform.c',
    'services.c',
    'video.c',
])

# Add architecture-specific headers.
env['CPPPATH'] += [Dir('arch/%s/include' % (config['EFI_ARCH']))]

# Get architecture-specific sources.
arch_sources = SConscript(dirs = ['arch/' + config['EFI_ARCH']], exports = vars)
sources = arch_sources + sources

# EFI uses UCS-2 strings.
env['CCFLAGS'] += ['-fshort-wchar']

# We build the loader as a relocatable ELF shared library, and then convert
# that into a PE binary for use with EFI. On IA32 we don't actually compile as
# PIC, but by compiling as a shared library we are relocatable.
env['LINKFLAGS'] += [
    '-Wl,-Bsymbolic', '-Wl,-shared', '-Wl,-znocombreloc', '-Wl,--no-undefined'
]

Return('sources')
