#
# Copyright (C) 2014 Alex Smith
#
# Permission to use, copy, modify, and/or distribute this software for any
# purpose with or without fee is hereby granted, provided that the above
# copyright notice and this permission notice appear in all copies.
#
# THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES
# WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF
# MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR
# ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
# WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN
# ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF
# OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.
#

Import('config', 'defaults', 'env')
from util import FeatureSources

sources = FeatureSources(config, [
    'console.c',
    'platform.c',
    'start.S',
])

# Build the stage 1 loaders.
env.LDScript('stage1/stage1.ld', 'stage1/stage1.ld.in')
stage1s = ['cdboot']
for f in stage1s:
    name = 'stage1/%s' % (f)

    env.Program('%s.elf' % (name), '%s.S' % (name), LIBS = [],
        LINKFLAGS = env['LINKFLAGS'] + ['-Wl,-T,${TARGET.dir}/stage1.ld', '-Wl,-N'])
    Depends('%s.elf' % (name), File('stage1/stage1.ld'))

    target = env.Command([name, '%s.lst' % (name)], '%s.elf' % (name), [
        Action("$OBJCOPY -O binary --strip-all $SOURCE ${TARGETS[0]}", '$GENCOMSTR'),
        Action('$OBJDUMP -d -m i386 -M i8086 $SOURCE > ${TARGETS[1]}', None),
    ])

    defaults.append(target)

# Set the linker script path.
env['LDSCRIPT'] = env.LDScript('link.ld', 'link.ld.in')

Return('sources')
