#
# SPDX-FileCopyrightText: (C) Alex Smith <alex@alex-smith.me.uk>
# SPDX-License-Identifier: ISC
#

include = {
    'config': {
        'PLATFORM': 'bios',
        'PLATFORM_BIOS': True,
        'TARGET_HAS_DISK': True,
        'TARGET_HAS_NET': True,
        'TARGET_HAS_UI': True,
        'TARGET_HAS_VIDEO': True,
        'DRIVER_CONSOLE_VGA': True,
        'DRIVER_SERIAL_NS16550': True,
        'TARGET_NS16550_IO': True,
        'DRIVER_CONSOLE_FB': True,
        'FB': True,
        'GUI_MENU': True,
    },
}
