#
# SPDX-FileCopyrightText: (C) Alex Smith <alex@alex-smith.me.uk>
# SPDX-License-Identifier: ISC
#

include = {
    'config': {
        'PLATFORM': 'efi',
        'PLATFORM_EFI': True,
        'TARGET_HAS_DISK': True,
        'TARGET_HAS_NET': True,
        'TARGET_HAS_UI': True,
        'TARGET_HAS_VIDEO': True,
        'DRIVER_CONSOLE_FB': True,
        'FB': True,
        'GUI_MENU': True,
    },
}
