#
# SPDX-FileCopyrightText: (C) Alex Smith <alex@alex-smith.me.uk>
# SPDX-License-Identifier: ISC
#

Import('config', 'env')
from util import FeatureSources

sources = FeatureSources(config, [
    'relocate.c',
    'start.S',
])

# Set the linker script path.
env['LDSCRIPT'] = env.LDScript('link.ld', 'link.ld.in')

# Build the final EFI binary.
env.Command(
    env['OUTDIR'].File('kbootia32.efi'),
    env['KBOOT'],
    Action(
        '$OBJCOPY -j .text -j .reloc -j .data -j .dynamic -j .rel ' +
            '-j .dynsym -j .bss --target=efi-app-ia32 $SOURCE $TARGET',
        '$GENCOMSTR'))

Return('sources')
