#
# SPDX-FileCopyrightText: (C) Alex Smith <alex@alex-smith.me.uk>
# SPDX-License-Identifier: ISC
#

Import('config', 'env')
from util import FeatureSources

sources = FeatureSources(config, [
    'loader/kboot.c',
    'loader/kboot_enter.S',

    'arch.c',
    'backtrace.c',
    'entry.S',
    'exception.c',
    'mmu.c',
    'time.c',
])

# No unaligned access (see loader.h).
env['CCFLAGS'] += ['-mno-unaligned-access']

# Prevent FPU code generation.
env['CCFLAGS'] += ['-mgeneral-regs-only']

# Warn on stack frames that are too large.
env['CCFLAGS'] += ['-Wframe-larger-than=768', '-Wno-address-of-packed-member']

# Default page size may be larger which can result in a large output binary.
env['LINKFLAGS'] += ['-Wl,-z,max-page-size=0x1000', '-Wl,-z,common-page-size=0x1000']

Return('sources')
