#
# SPDX-FileCopyrightText: (C) Alex Smith <alex@alex-smith.me.uk>
# SPDX-License-Identifier: ISC
#

vars = ['config', 'env']

Import(*vars)
from util import FeatureSources

sources = FeatureSources(config, [
    'loader/linux.c',
    'loader/multiboot.c',
])

arch_sources = SConscript(dirs = ['amd64' if config['64BIT'] else 'ia32'], exports = vars)
sources = arch_sources + sources

Return('sources')
