#
# Copyright (C) 2009-2021 Alex Smith
#
# Permission to use, copy, modify, and/or distribute this software for any
# purpose with or without fee is hereby granted, provided that the above
# copyright notice and this permission notice appear in all copies.
#
# THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES
# WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF
# MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR
# ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
# WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN
# ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF
# OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.
#

Import('config', 'env')
from util import FeatureSources

# Handle dependencies.
if any(k.startswith('DRIVER_SERIAL_') and v for k, v in config.items()):
    config['DRIVER_CONSOLE_SERIAL'] = True

sources = FeatureSources(config, [
    ('DRIVER_SERIAL_NS16550', 'serial/ns16550.c'),
    ('DRIVER_SERIAL_PL011', 'serial/pl011.c'),

    ('DRIVER_CONSOLE_FB', 'console/fb.c'),
    ('DRIVER_CONSOLE_FB', 'console/font.c'),
    ('DRIVER_CONSOLE_SERIAL', 'console/serial.c'),
    ('DRIVER_CONSOLE_VGA', 'console/vga.c'),
])

Return('sources')
