#
# SPDX-FileCopyrightText: (C) Alex Smith <alex@alex-smith.me.uk>
# SPDX-License-Identifier: ISC
#

Import('config', 'env')
from util import FeatureSources

# Handle dependencies.
if any(k.startswith('DRIVER_SERIAL_') and v for k, v in config.items()):
    config['DRIVER_CONSOLE_SERIAL'] = True

sources = FeatureSources(config, [
    ('DRIVER_CONSOLE_FB',           'console/fb.c'),
    ('DRIVER_CONSOLE_FB',           'console/font.c'),
    ('DRIVER_CONSOLE_SERIAL',       'console/serial.c'),
    ('DRIVER_CONSOLE_VGA',          'console/vga.c'),

    ('DRIVER_DISK_RAMDISK',         'disk/ramdisk.c'),

    ('DRIVER_BCM283X_FIRMWARE',     'platform/bcm283x/firmware.c'),
    ('DRIVER_BCM283X_MBOX',         'platform/bcm283x/mbox.c'),

    ('DRIVER_SERIAL_NS16550',       'serial/ns16550.c'),
    ('DRIVER_SERIAL_PL011',         'serial/pl011.c'),

    ('DRIVER_VIDEO_BCM283X',        'video/bcm283x.c'),
])

Return('sources')
