#
# SPDX-FileCopyrightText: (C) Alex Smith <alex@alex-smith.me.uk>
# SPDX-License-Identifier: ISC
#

vars = ['config', 'env']

Import(*vars)
from util import FeatureSources

sources = FeatureSources(config, [
    'loader/kboot.c',

    'console.c',
    'memory.c',
    'platform.c',
])

# Add architecture-specific headers.
env['CPPPATH'] += [Dir('arch/%s/include' % (config['ARCH']))]

# Get architecture-specific sources.
arch_sources = SConscript(dirs = ['arch/' + config['ARCH']], exports = vars)
sources = arch_sources + sources

# Build the final loader binary.
kboot = env.Command(
    env['OUTDIR'].File('kboot.bin'),
    env['KBOOT'],
    Action('$OBJCOPY -O binary --strip-all $SOURCE $TARGET', '$GENCOMSTR'))

Return('sources')
